version: '3'

services:

  hello-world:
    container_name: hello-world
    image: hello-world:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2800M
